### PR TITLE
Re-apply perl-in-space fixes

### PR DESCRIPTION
**Pull request by mohawk2**
Without these changes, the code will not build on eg Windows where there is a space in Perl's path.

### CODE REVIEW

**Comment by mohawk2** [comment]
This will need a fix in EUMM to handle `-L"/some/place"`, almost certainly using `Text::ParseWords::shellwords` in place of `split ' ', ...`.

**Comment by mohawk2** [comment]
The EUMM fix has been made but is not needed here; instead I have made the space-quoting for `-L` locations conditional on whether they have spaces. @h-vn I believe this is ready for review!

**Comment by h-vn** [comment]
The related CPAN request tracker ticket is [#121915](https://rt.cpan.org/Public/Bug/Display.html?id=121915)

**Comment by h-vn** [comment]
Thanks for this. I'll make a developer release from master next.

**Pull request merged**
