### PR TITLE
OpenVMS build update

### PR DESCRIPTION
**Pull request by craigberry**

### CODE REVIEW

**Comment by h-vn** [comment]
About the _const/not-const mismatch in i2d_OCSP_CERTID call_, does is cause compile to fail or is it just a warning? The reason I'm asking is that with OpenSSL 3.0.0 the cast is not needed anymore because the OpenSSL headers have been updated with corrected definitions.

In other words, I'd avoid adding the cast because it's already fixed in the latest OpenSSL. Then again I understand that it triggers warning that trigger compile logs with the currently used versions.

**Comment by craigberry** [comment]
It's a compiler warning that triggers a make failure. If there's a different way to handle it, I'm open to that but this is what I could think of.  OpenSSL 3.0 is planned for this platform but I don't know when it's likely to be delivered.

**Comment by h-vn** [comment]
I agree that a cast is needed because it now triggers a failure. One option could be to add a pre-processor directive to check library and version, but I'm not sure if it's worth doing it just for a cast.

In any case, can you add an appropriate entry in the Changes file too? I'm no familiar with VMS so I wouldn't want summarise the change and get it wrong while doing it.

**Comment by craigberry** [comment]
I've pushed some entries to Changes, making a guess about the next version number.  Obviously you'll update that to whatever you want when you are preparing the next release.

**Comment by h-vn** [comment]
Merged with thanks!

**Pull request merged**
