### PR TITLE
Beef up CI.

### PR DESCRIPTION
**Pull request by FGasper**

### CODE REVIEW

**Comment by FGasper** [comment]
https://github.com/radiator-software/p5-net-ssleay/actions/runs/3144732650/jobs/5111124301#step:3:1007
@chrisnovakovic I think the FreeBSD/OpenSSL failure here might be legit? I admittedly haven’t investigated.

**Comment by h-vn** [comment]
Seems to be #272 and #394 issue. Apparently recent FreeBSD releases have disabled OpenSSL 3.0 legacy provider completely.

**Comment by FGasper** [comment]
@h-vn Yeah I saw those issues after submitting. I guess for now I’ll comment that one out.

**Comment by h-vn** [comment]
Thanks, merging now. I'll follow up with the other pull requests and we'll see how it goes.

**Comment by h-vn** [comment]
Seems that [cygwin/cygwin-install-action](https://github.com/cygwin/cygwin-install-action) would the fix for cygwin failing. I'll give it a try.

**Comment by FGasper** [comment]
Several of my Perl repos show use of the Cygwin CI, FYI.

**Comment by h-vn** [comment]
Have you seen this before? It seems not to be an unique error, based on Google search, but I haven't looked into this in detail yet. The change was just the action, as you can see here: https://github.com/radiator-software/p5-net-ssleay/tree/GH-408-fix-cygwin-ci

github-ci-fail

I can also look into this, but please let me know if there's a quick fix for this.

**Comment by FGasper** [comment]
I’ll try to look later. Looks like your path isn’t set properly.

You might just copy-paste from one of my own Perl repos.

-FG

**Comment by h-vn** [comment]
Thanks for the hint. This fixes the problem, taken from your [p5-Net-LibNFS](https://github.com/FGasper/p5-Net-LibNFS) repository. I first thought the problem was with `perl -V` when it was about invoking bash.exe. Thanks again!

```
       - run: perl -V
-        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
```

**Pull request merged**
