### PR TITLE
Adding in methods for STACK_OF(X509) and X509_STORE_CTX objects

### PR DESCRIPTION
**Pull request by DanFreed**
This exposes a some new methods to access the certificate and the cert chain in a X509_STORE_CTX: 

- X509_STORE_CTX_get0_cert 
- X509_STORE_CTX_get1_chain

This also exposes some methods for manipulation of STACK_OF(X509) objects:

- sk_X509_insert
- sk_X509_num
- sk_X509_delete
- sk_X509_unshift
- sk_X509_shift  
- sk_X509_pop

### CODE REVIEW

**Comment by h-vn** [comment]
Would it be ok with you if I squash the changes, force push them and then apply some minor fixes as a separate commit? I've looked at this pull request and I'd like to merge it after some tidying up, such as adding change history, document fixes and TLS library version guards.

**Comment by DanFreed** [comment]
That would be fine by me.  Thanks for addressing this.

-Dan

**Comment by h-vn** [comment]
I've now squashed your commits to a single commit and then added a separate commit where I've done the minor updates I mentioned above.

There's also one API change I noticed: `X509_STORE_CTX_get0_cert` and `sk_X509_delete` return values were corrected from `int` to `X509 *.` If you are already using those functions, you may want to check how those return values are used.

If the pull request looks good to you, I can then do a squash and merge everything as a single commit.

**Comment by DanFreed** [comment]
The changes look good.

**Pull request merged**
