### PR TITLE
Expose x509_get0_serialNumber

### LINKED ISSUE #76: Add X509_get0_serialNumber
X509_get0_serialNumber was added to OpenSSL 1.1.0.

For more information, see:
https://www.openssl.org/docs/manmaster/man3/X509_get0_serialNumber.html

### PR DESCRIPTION
**Pull request by FractalBoy**
Resolves #76

### CODE REVIEW

**Comment by chrisnovakovic** [comment]
Thanks for taking care of this, Marc - any chance you could also write some tests for `X509_get0_serialNumber` and add them to the test suite, please?

**Comment by FractalBoy** [comment]
@chrisnovakovic, the result of this doesn't appear to be any different than X509_get_serialNumber. It's not actually a const pointer. I'm able to change the value of the ASN1_INTEGER struct.

When I try to do the same in C code, I get a compiler warning and a seg fault. I don't get a seg fault in Perl, which is surprising. It just seems to happily change the value of the ASN1_INTEGER.

I'm questioning whether this function actually has any utility for Perl.

**Comment by FractalBoy** [comment]
Nevermind - there was a different problem with my C code that was causing the seg fault.

Still, the only purpose of this function appears to be the intention that you do not wish to change the members of the ASN1_INTEGER struct.

**Comment by FractalBoy** [comment]
I'm not sure why the build is failing. I have the #if directive that checks the version of openssl.

**Comment by chrisnovakovic** [comment]
I suspect it's because you meant to check for at least version `0x10100000L` rather than `0x1010000L` 🙂 Actually the version to check for would be `0x10100008L`, as `X509_get0_serialNumber` was [added between OpenSSL 1.1.0-pre7 and 1.1.0-pre8](https://github.com/openssl/openssl/commit/68c12bfc6601d40e85146f36f26fe8ff0472f36b) - or you could just check for the stable release of OpenSSL 1.1.0 (`0x1010000fL`).

**Comment by FractalBoy** [comment]
That's actually what I had originally, but I changed it when I noticed that the tests weren't running. Weird.

I'll use 0x1010000fL. Thanks!

**Comment by h-vn** [comment]
I noticed a check for LibreSSL 2.8.1 was needed. Now it should compile on all OpenSSL and LibreSSL versions.

**Comment by chrisnovakovic** [comment]
In the process of performing a few minor fixups and then merging this manually, hold tight...

**Comment by chrisnovakovic** [comment]
Merged manually (as b35d10). Thanks again!

**Pull request closed without merging**
