### PR TITLE
Expose additional functions and constants

### PR DESCRIPTION
**Pull request by FractalBoy**
These functions and constants are necessary to verify a certificate using a hash
directory outside of an SSL/TLS connection.

I exposed the following functions:

X509_STORE_CTX_init
X509_STORE_CTX_free
X509_STORE_new
X509_STORE_free
X509_STORE_add_lookup
X509_LOOKUP_hash_dir
X509_LOOKUP_add_dir

And the following constants:

X509_FILETYPE_ASN1
X509_FILETYPE_DEFAULT
X509_FILETYPE_PEM

### CODE REVIEW

**Comment by FractalBoy** [comment]
@chrisnovakovic is there anything you need me to do before this can be merged? any concerns with adding these new things?

**Comment by h-vn** [comment]
I think it's good as it is. I will merge it soon and add an entry to Changes when preparing for the next developer release. These both will happen soon.

**Comment by h-vn** [comment]
Big thanks for these!

**Comment by FractalBoy** [comment]
@h-vn thanks so much!

**Pull request merged**
