### PR TITLE
Expose functions to allow reading multiple pems from file and creating untrusted chain

### PR DESCRIPTION
**Pull request by FractalBoy**
These functions allow one to read in a PEM file with multiple certificates as a STACK_OF(X509_INFO). These functions allow you to determine the size of the STACK_OF(X509_INFO) and value at an index, which allows you to loop over the stack. There is a function to retrieve the X509 structure from each X509_INFO structure in the stack. Then you can create a new STACK_OF(X509) and push the X509 structures onto the new stack. You can then pass this STACK_OF(X509) to X509_STORE_CTX_init which will allow you to add additional untrusted certificates to the chain for verification.

### CODE REVIEW

**Comment by FractalBoy** [comment]
@h-vn I have another pull request - I realized I was missing some functions necessary to complete the certificate chain. Could you merge this as well?

**Comment by FractalBoy** [comment]
Sorry to be a pest, but @h-vn - thoughts?

**Comment by h-vn** [comment]
No worries about pinging, new functions are always welcome.

Do you think you could write some tests for these functions? For example, P_get_X509_INFO_x509 does not expose an existing function, so a test would be especially useful to check that it will continue working as it's supposed to do.

One thing I noticed about stack functions, is that they seem to use const qualifier. For example:
https://www.openssl.org/docs/man1.1.0/man3/DEFINE_STACK_OF.html

Should the newly exposed  sk_ functions also use const?

**Comment by FractalBoy** [comment]
I added some tests and the const qualifier where I see it documented.

I'm not sure I 100% understand the difference when dealing with XSUBs - the const qualifier appears to be primarily for protections during compile time. By using Perl, we don't get those protections. Or, am I missing something?

**Comment by h-vn** [comment]
I think the use of const, and interfaces that use const arguments, such as x509_get0_serialNumber in  pull request #112, can be considered a way to clarify the intention.

For example, using x509_get0_serialNumber instead of X509_get_serialNumber makes it clear that the person who wrote the code wants the argument not to be changed and acknowledges that the return value is treated as immutable.

What I know that compilers output can depend on const. For example, the snippet below prints 1 three times when compiled with clang on Mac
```c
#include <stdio.h>

int main(void)
{
  // volatile const int c = 1;
  const int c = 1;
  // int c = 1;
  printf("c: %d\n", c);

  int *c1 = &c;
  printf("c: %d\n", c);

  *c1 = 2;
  printf("c: %d\n", c);

  return 0;
}
```

What happens when XS with consts is processed may change things, but based on my above trial snippet, I'd try to match consts as much as possible.

I guess this is ready for a merge soon. Thanks!

**Comment by FractalBoy** [comment]
Thanks for the explanation!

**Comment by h-vn** [comment]
Could you check travis build log and see what can be done for compilation warnings. For example, Pler 5.28 with OpenSSL 1.0.2q:
```
cc -c  -I"/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.0.2q/include" -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"1.86_07\" -DXS_VERSION=\"1.86_07\" -fPIC "-I/home/travis/perl5/perlbrew/perls/5.28.1/lib/5.28.1/x86_64-linux/CORE"   SSLeay.c
SSLeay.c: In function ‘XS_Net__SSLeay_PEM_X509_INFO_read_bio’:
SSLeay.c:14226:2: warning: passing argument 2 of ‘PEM_X509_INFO_read_bio’ from incompatible pointer type [enabled by default]
  RETVAL = PEM_X509_INFO_read_bio(bio, stack, cb, u);
  ^
In file included from /home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.0.2q/include/openssl/ssl.h:162:0,
                 from SSLeay.xs:168:
/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.0.2q/include/openssl/pem.h:413:22: note: expected ‘struct stack_st_X509_INFO *’ but argument is of type ‘struct stack_st_X509 *’
 STACK_OF(X509_INFO) *PEM_X509_INFO_read_bio(BIO *bp, STACK_OF(X509_INFO) *sk,
                      ^
```
With Perl 5.28 and OpenSSL 1.1.1a  there are two additional, const related warnings:
```
SSLeay.c: In function ‘XS_Net__SSLeay_sk_X509_free’:
SSLeay.c:14316:2: warning: passing argument 1 of ‘sk_X509_free’ discards ‘const’ qualifier from pointer target type [enabled by default]
  sk_X509_free(stack);
  ^
In file included from /home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/crypto.h:23:0,
                 from /home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/bio.h:20,
                 from /home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/err.h:21,
                 from SSLeay.xs:164:
/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/safestack.h:51:29: note: expected ‘struct stack_st_X509 *’ but argument is of type ‘const struct stack_st_X509 *’
     static ossl_inline void sk_##t1##_free(STACK_OF(t1) *sk) \
                             ^
/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/safestack.h:130:29: note: in expansion of macro ‘SKM_DEFINE_STACK_OF’
 # define DEFINE_STACK_OF(t) SKM_DEFINE_STACK_OF(t, t, t)
                             ^
/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/x509.h:99:1: note: in expansion of macro ‘DEFINE_STACK_OF’
 DEFINE_STACK_OF(X509)
 ^
```
and right after the above:
```
SSLeay.c: In function ‘XS_Net__SSLeay_sk_X509_push’:
SSLeay.c:14336:2: warning: passing argument 2 of ‘sk_X509_push’ discards ‘const’ qualifier from pointer target type [enabled by default]
  RETVAL = sk_X509_push(stack, data);
  ^
In file included from /home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/crypto.h:23:0,
                 from /home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/bio.h:20,
                 from /home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/err.h:21,
                 from SSLeay.xs:164:
/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/safestack.h:68:28: note: expected ‘struct X509 *’ but argument is of type ‘const struct X509 *’
     static ossl_inline int sk_##t1##_push(STACK_OF(t1) *sk, t2 *ptr) \
                            ^
/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/safestack.h:130:29: note: in expansion of macro ‘SKM_DEFINE_STACK_OF’
 # define DEFINE_STACK_OF(t) SKM_DEFINE_STACK_OF(t, t, t)
                             ^
/home/travis/build/radiator-software/p5-net-ssleay/openssl_version_cache/build/openssl-1.1.1a/include/openssl/x509.h:99:1: note: in expansion of macro ‘DEFINE_STACK_OF’
 DEFINE_STACK_OF(X509)
 ^
```

**Comment by h-vn** [comment]
The warning related to `PEM_X509_INFO_read_bio` seems to be easy to fix. The accessor in SSLeay.xs should simply say that `stack` is `STACK_OF(X509_INFO)` instead of `STACK_OF(X509)`. Does this seem ok?

**Comment by h-vn** [comment]
And the `const` warnings seem to get back to what was discussed above. I'm not sure if there's more what can be done for those.

**Comment by FractalBoy** [comment]
Good catch - I fixed those warnings.

**Comment by h-vn** [comment]
Thanks Marc!

**Comment by FractalBoy** [comment]
You're welcome!

**Pull request merged**
